[package]
name = "urids"
version = "0.0.1"
authors = ["Johannes Mueller <github@johannes-mueller.org>"]
edition = "2018"

[dependencies.lv2]
version = "0.5.1"
features = ["lv2-buf-size", "lv2-options", "lv2-parameters", "lv2-ui"]
