[package]
name = "envolvigo-lv2-ui"
version = "0.0.1"
authors = ["Johannes Mueller <github@johannes-mueller.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
cascade = "0.1.4"

lv2 = "0.5.1"
lv2-sys = "1.1.0"

cairo-rs = "0.8.1"
pango = "0.8.0"
pangocairo = "0.9.0"

pugl-ui = "0.1.2"
pugl-sys = "0.2.0"

lv2-ui = { git = "https://github.com/johannes-mueller/rust-lv2.git", branch="johmue-merges" }
jilar = { git = "https://github.com/johannes-mueller/jilar.git" }

urids = { path = "../urids" }
